[#3073] Show data-groups source columns in merge-dataset
akvo/akvo-lumen pull request #3075
Opened 2020-12-11 20:44 UTC by tangrammer

- [ ] **Update release notes if necessary**

<img width="1258" alt="Screenshot 2020-12-11 at 21 29 47" src="https://user-images.githubusercontent.com/731829/101953061-f77d1f80-3bf9-11eb-964f-effdcd5d40aa.png">

2020-12-12 19:46 UTC, iperdomo requested changes
Minor changes

2020-12-12 19:46 UTC, iperdomo commented on client/src/components/transformation/merge/SourceMergeOptions.jsx
> +function capitalizeFirstLetter(string) {
Since we have lodash as dependency, we can use [capitalize](https://lodash.com/docs/4.17.15#capitalize) ?

2020-12-12 19:46 UTC, iperdomo commented on client/src/components/transformation/merge/SourceMergeOptions.jsx
> +        return <div key={groupName}><div className="groupName">{capitalizeFirstLetter(groupName)}</div>{colsData}</div>;
I would suggest to add a different *style*, similar of what we do with drop-downs. There the group names are *smaller*
![2020-12-12-204418_1920x1080_scrot](https://user-images.githubusercontent.com/178474/101993440-1394c580-3cbb-11eb-8977-06ee832b5795.png)

2020-12-12 19:47 UTC, iperdomo commented on client/src/components/transformation/merge/SourceMergeOptions.jsx
> +        return <div key={groupName}><div className="groupName">{capitalizeFirstLetter(groupName)}</div>{colsData}</div>;
Not sure now if *smaller* or **bold** is the way to go.

2020-12-14 09:31 UTC, tangrammer commented
styles after the change
![Screenshot 2020-12-14 at 10 31 03](https://user-images.githubusercontent.com/731829/102064423-90c55500-3df7-11eb-8488-484eba048ec5.png)

2020-12-14 09:49 UTC, merged