Issue/2794 dashboard visualization error
akvo/akvo-lumen pull request #3137
Opened 2021-06-17 14:42 UTC by melowsoft

- [ ] **Update release notes if necessary**

- Added Error screen for dashbaord error
- Fixed undefined error

2021-06-17 15:49 UTC, iperdomo requested changes
I think this branch has a mixture of 2 different problems:

* Adding a dataset within an existing collection
* Showing an error message when the dashboard doesn't exist

Is this case? 🤔 If so, let's split the changes in 2 branches, one for the dataset problem, other for the visualization error

2021-06-17 15:49 UTC, iperdomo commented on client/src/actions/collection.js
> +    console.log( "i got here finally, where the bug is")
Please remove those debugging logging

2021-06-17 15:52 UTC, iperdomo commented
I would also suggest to fix your committer settings, right now is using a non recognized email address.

https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address

2021-06-18 12:38 UTC, iperdomo commented
@melowsoft this branch still has changes that are *not* related to the issue. Can you update/fix this branch so we have only the necessary changes for the issue at hand?

2021-06-18 13:47 UTC, melowsoft commented
> @melowsoft this branch still has changes that are _not_ related to the issue. Can you update/fix this branch so we have only the necessary changes for the issue at hand?

okay, I will fix this

2021-06-18 14:42 UTC, closed without merging